# Generated by Django 5.1.5 on 2025-02-06 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolamp_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esp32device',
            name='user',
        ),
        migrations.AddField(
            model_name='esp32device',
            name='user',
            field=models.ManyToManyField(related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
