# Generated by Django 5.1.5 on 2025-03-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolamp_api', '0004_alter_airqualitydata_aqi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitydata',
            name='aqi',
            field=models.IntegerField(editable=False),
        ),
    ]
