# Generated by Django 5.1.5 on 2025-03-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(unique=True)),
                ('relay_status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=5)),
            ],
        ),
    ]
