# Generated by Django 5.1.5 on 2025-03-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppControl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceControl',
            new_name='RelayControl',
        ),
    ]
